### ISSUE TITLE
Rename Go SDK from rubrikcdm to rubrik

### ISSUE THREAD

**Issue by jaapbrasser** [rubrikinc/rubrik-sdk-for-go#43]
**Describe the solution you'd like**

For the Terraform certification I would like to rename the sdk from rubrikcdm to rubrik

**Additional context**

In order to do this, all documentation and example will have to be updated to accommodate for this change.

This is related to the this issue on the Terraform provider repository [Terraform Provider Development Program - Review](https://github.com/rubrikinc/terraform-provider-rubrik/issues/66)

**Comment by drew-russell** [comment]
Do you mean the actual `rubrikcdm` package? If so we don't want to do this for two main reasons.

1. This aligns which how the Python SDK is setup.
2. We need it to be CDM specific to distinguish from the upcoming Polaris SDK

**Comment by shamsway** [comment]
@drew-russell this was a request from HashiCorp to certify our Terraform provider - https://github.com/rubrikinc/terraform-provider-rubrik/issues/66. We may be able to push back. 

We can discuss later today if you like. Perhaps we should consider structuring this (and other SDKs) in a nested fashion like our Ansible Collection. `rubrik.cdm` for the current SDK and `rubrik.polaris` for the upcoming SDK. It would be a painful change but it may be worth considering.

**Comment by jaapbrasser** [comment]
Closing this issue as this is no longer required.
