### ISSUE TITLE
Create a file download job from a fileset backup

### ISSUE THREAD

**Issue by fideltak** [rubrikinc/rubrik-sdk-for-go#45]
**Is your feature request related to a problem? Please describe.**

I want to copy some files to containers on k8s from backup.
So I'm trying to retrieve backup file by using k8s init container by using this SDK.
However SDK seems not to support creating a file download job from a fileset backup for now.

**Describe the solution you'd like**
Support feature for creating a file download job.  
I forked this repo and added this feature.  
https://github.com/fideltak/rubrik-sdk-for-go  
I'm ready to PR.

**Describe alternatives you've considered**
Support restore files for containers on rubrik side.

**Additional context**

**Comment by drew-russell** [comment]
@fideltak feel free to submit a PR and we can take a look

**Comment by shamsway** [comment]
Addressed by #46
