### ISSUE TITLE
Typo in quick-start.md

### ISSUE THREAD

**Issue by keilma** [rubrikinc/rubrik-sdk-for-go#51]
Hi, 

I think there is a typo in quick-start.md:

`When calling rubrikcdm.Connect(), it will attempt to read the Rubrik Cluster credentials from the following environment variables:`

This should be rubrikcdm.ConnectEnv() as Connect() does not read the credentials from the environment variables.

Kind regards
Marcel

**Comment by jaapbrasser** [comment]
Thanks for contributing @keilma! I've added some small changes to your pr as I noticed a broken code block in there as well.
